import Foundation

enum LinkerConfigGenerator {
    static func generate(for config: CartridgeConfig) -> String {
        switch config.mapping {
        case .loROM:
            return generateLoROM(config)
        case .hiROM, .exHiROM:
            return generateHiROM(config)
        case .sa1:
            return generateSA1(config)
        }
    }

    // MARK: - LoROM

    private static func generateLoROM(_ config: CartridgeConfig) -> String {
        let bankCount = config.romSizeKB / 32
        var memory = """
        MEMORY {
            ZEROPAGE:   start = $00,     size = $100, type = rw;
            RAM:        start = $0100,   size = $1F00, type = rw;

        """

        if config.sramSizeKB > 0 {
            let sramSize = String(format: "$%04X", config.sramSizeKB * 1024)
            memory += "    SRAM:       start = $700000, size = \(sramSize), type = rw;\n"
        }

        // ROM banks
        let romBanks = min(bankCount, 64)
        for i in 0..<min(romBanks, 8) {
            let start = String(format: "$%02X8000", i)
            let name = i == 0 ? "ROM0" : "ROM\(i)"
            memory += "    \(name.padding(toLength: 11, withPad: " ", startingAt: 0)): start = \(start), size = $8000, fill = yes;\n"
        }

        // Header at fixed location
        memory += "    ROMH:       start = $00FFB0, size = $50;\n"
        memory += "}\n"

        var segments = """

        SEGMENTS {
            ZEROPAGE:   load = ZEROPAGE, type = zp;
            BSS:        load = RAM, type = bss;

        """

        if config.sramSizeKB > 0 {
            segments += "    SRAM:       load = SRAM, type = bss;\n"
        }

        segments += """
            CODE:       load = ROM0, type = ro;
            RODATA:     load = ROM1, type = ro;
            GFX:        load = ROM2, type = ro;
            HEADER:     load = ROMH, type = ro;
        }

        """

        return "# Generated by SNES Studio — LoROM \(config.romSizeKB) KB\n\n" + memory + segments
    }

    // MARK: - HiROM / ExHiROM

    private static func generateHiROM(_ config: CartridgeConfig) -> String {
        let bankCount = config.romSizeKB / 64
        var memory = """
        MEMORY {
            ZEROPAGE:   start = $00,       size = $100, type = rw;
            RAM:        start = $0100,     size = $1F00, type = rw;

        """

        if config.sramSizeKB > 0 {
            let sramSize = String(format: "$%04X", config.sramSizeKB * 1024)
            memory += "    SRAM:       start = $206000, size = \(sramSize), type = rw;\n"
        }

        let romBanks = min(bankCount, 64)
        for i in 0..<min(romBanks, 4) {
            let bank = 0xC0 + i
            let start = String(format: "$%02X0000", bank)
            let name = "ROM\(i)"
            memory += "    \(name.padding(toLength: 11, withPad: " ", startingAt: 0)): start = \(start), size = $10000, fill = yes;\n"
        }

        memory += "    ROMH:       start = $00FFB0, size = $50;\n"
        memory += "}\n"

        var segments = """

        SEGMENTS {
            ZEROPAGE:   load = ZEROPAGE, type = zp;
            BSS:        load = RAM, type = bss;

        """

        if config.sramSizeKB > 0 {
            segments += "    SRAM:       load = SRAM, type = bss;\n"
        }

        segments += """
            CODE:       load = ROM0, type = ro;
            RODATA:     load = ROM1, type = ro;
            HEADER:     load = ROMH, type = ro;
        }

        """

        let label = config.mapping == .exHiROM ? "ExHiROM" : "HiROM"
        return "# Generated by SNES Studio — \(label) \(config.romSizeKB) KB\n\n" + memory + segments
    }

    // MARK: - SA-1

    private static func generateSA1(_ config: CartridgeConfig) -> String {
        var memory = """
        MEMORY {
            ZEROPAGE:   start = $00,       size = $100, type = rw;
            RAM:        start = $0100,     size = $1F00, type = rw;
            SA1RAM:     start = $003000,   size = $0800, type = rw;

        """

        if config.sramSizeKB > 0 {
            let sramSize = String(format: "$%04X", config.sramSizeKB * 1024)
            memory += "    SRAM:       start = $400000, size = \(sramSize), type = rw;\n"
        }

        memory += """
            ROM0:       start = $C00000, size = $10000, fill = yes;
            ROM1:       start = $C10000, size = $10000, fill = yes;
            ROMH:       start = $00FFB0, size = $50;
        }

        """

        var segments = """

        SEGMENTS {
            ZEROPAGE:   load = ZEROPAGE, type = zp;
            BSS:        load = RAM, type = bss;
            SA1BSS:     load = SA1RAM, type = bss;

        """

        if config.sramSizeKB > 0 {
            segments += "    SRAM:       load = SRAM, type = bss;\n"
        }

        segments += """
            CODE:       load = ROM0, type = ro;
            SA1CODE:    load = ROM1, type = ro;
            RODATA:     load = ROM0, type = ro;
            HEADER:     load = ROMH, type = ro;
        }

        """

        return "# Generated by SNES Studio — SA-1 \(config.romSizeKB) KB\n\n" + memory + segments
    }
}
