import Foundation

enum SNESButton: String, CaseIterable, Codable, Identifiable {
    case a, b, x, y, l, r, start, select
    case up, down, left, right

    var id: String { rawValue }

    var label: String {
        switch self {
        case .a: return "A"
        case .b: return "B"
        case .x: return "X"
        case .y: return "Y"
        case .l: return "L"
        case .r: return "R"
        case .start: return "Start"
        case .select: return "Select"
        case .up: return "Up"
        case .down: return "Down"
        case .left: return "Left"
        case .right: return "Right"
        }
    }

    var bitMask: String {
        switch self {
        case .r:      return "#$0010"
        case .l:      return "#$0020"
        case .x:      return "#$0040"
        case .a:      return "#$0080"
        case .right:  return "#$0100"
        case .left:   return "#$0200"
        case .down:   return "#$0400"
        case .up:     return "#$0800"
        case .start:  return "#$1000"
        case .select: return "#$2000"
        case .y:      return "#$4000"
        case .b:      return "#$8000"
        }
    }
}

struct ButtonAction: Equatable, Codable {
    var label: String
    var asmRoutine: String

    static let empty = ButtonAction(label: "", asmRoutine: "")
}

struct ControllerMapping: Equatable, Codable {
    var mappings: [String: ButtonAction] = [:]  // keyed by SNESButton.rawValue

    subscript(button: SNESButton) -> ButtonAction {
        get { mappings[button.rawValue] ?? .empty }
        set { mappings[button.rawValue] = newValue }
    }

    func generateASM() -> String {
        var lines: [String] = []
        lines.append("; ═══════════════════════════════════════════")
        lines.append("; Input handler — generated by SNES Studio")
        lines.append("; ═══════════════════════════════════════════")
        lines.append("")
        lines.append(".proc ReadInput")
        lines.append("    lda $4218          ; Read Joypad 1")
        lines.append("    sta JoypadState")
        lines.append("")

        for button in SNESButton.allCases {
            let action = self[button]
            guard !action.asmRoutine.isEmpty else { continue }
            lines.append("    ; \(button.label) → \(action.label)")
            lines.append("    lda JoypadState")
            lines.append("    and \(button.bitMask)")
            lines.append("    beq @skip_\(button.rawValue)")
            lines.append("    jsr \(action.asmRoutine)")
            lines.append("@skip_\(button.rawValue):")
            lines.append("")
        }

        lines.append("    rts")
        lines.append(".endproc")
        lines.append("")
        lines.append("JoypadState: .word 0")
        return lines.joined(separator: "\n")
    }
}
