import SwiftUI

struct SidebarSection: Identifiable {
    let id: String
    let level: PyramidLevel
    var items: [SidebarItem]
    var isExpanded: Bool = true
}

struct SidebarItem: Identifiable, Hashable {
    let id: String
    let label: String
    let icon: String
    let level: PyramidLevel
    var badge: String? = nil
    var isAutoGenerated: Bool = false
    var filePath: URL? = nil
    var indent: Int = 0

    func hash(into hasher: inout Hasher) { hasher.combine(id) }
    static func == (lhs: SidebarItem, rhs: SidebarItem) -> Bool { lhs.id == rhs.id }
}

// MARK: - Dynamic sections from project

extension SidebarSection {
    static func sectionsFromProject(_ project: SNESProject) -> [SidebarSection] {
        let srcDir = project.sourceDirectoryURL
        let sourceItems = project.sourceFiles.map { filename in
            SidebarItem(
                id: filename,
                label: filename,
                icon: "doc.text",
                level: .logique,
                filePath: srcDir?.appendingPathComponent(filename)
            )
        }

        return [
            SidebarSection(
                id: "atelier",
                level: .atelier,
                items: [
                    SidebarItem(id: "palettes",   label: "Palettes",   icon: "paintpalette",  level: .atelier),
                    SidebarItem(id: "tiles",      label: "Tiles",      icon: "square.grid.3x3", level: .atelier),
                    SidebarItem(id: "tilemaps",   label: "Tilemaps",   icon: "map",           level: .atelier),
                    SidebarItem(id: "sprites",    label: "Sprites",    icon: "figure.run",    level: .atelier),
                    SidebarItem(id: "audio",      label: "Audio",      icon: "music.note",    level: .atelier),
                    SidebarItem(id: "controleur", label: "Controller", icon: "gamecontroller", level: .atelier),
                ]
            ),
            SidebarSection(
                id: "orchestre",
                level: .orchestre,
                items: [
                    SidebarItem(id: "niveaux",     label: "Screens",      icon: "square.grid.3x3.fill", level: .orchestre),
                ]
            ),
            SidebarSection(id: "logique", level: .logique, items: sourceItems),
            SidebarSection(
                id: "hardware",
                level: .hardware,
                items: [
                    SidebarItem(id: "cartouche",    label: "Cartridge",    icon: "cpu",             level: .hardware),
                    SidebarItem(id: "registres",    label: "Registers",    icon: "list.clipboard",  level: .hardware),
                    SidebarItem(id: "memoire",      label: "Memory",      icon: "memorychip",      level: .hardware),
                    SidebarItem(id: "vram",         label: "VRAM",         icon: "photo.artframe",  level: .hardware),
                    SidebarItem(id: "couches_bg",   label: "BG Layers",   icon: "square.3.layers.3d", level: .hardware),
                    SidebarItem(id: "rom_analyzer", label: "ROM Analyzer", icon: "magnifyingglass", level: .hardware),
                ]
            ),
        ]
    }
}

